package codegen

import (
	"fmt"
	"strings"
)

type JASM struct {
	code                    *Code
	procedureDefinitionName string
	labelID                 int
	pst                     *StackType
	endIfLabel              string
	elseLabel               string
}

func NewJASM() *JASM {
	return &JASM{
		code: NewCode(),
		pst:  NewStackType(),
	}
}

func (j *JASM) StartMainClass(name string) {
	j.addLine("// Code generated by POJ 0.1")
	j.addLine(fmt.Sprintf("public class %s {", name))
	j.incTab()
}

func (j *JASM) FinishMainClass() {
	j.decTab()
	j.addLine("}")
}

func (j *JASM) StartProcedureStatement(name string) {
	j.procedureDefinitionName = name
}

func (j *JASM) FinishProcedureStatement() {
	if j.procedureDefinitionName == "writeln" {
		j.addStaticPrintStream()
		j.addInvokeVirtualPrintln()
	}

	j.procedureDefinitionName = ""
}

func (j *JASM) StartParameter() {
	if j.procedureDefinitionName == "write" || j.procedureDefinitionName == "writeln" {
		j.addStaticPrintStream()
	}
}

func (j *JASM) FinishParameter() {
	if j.procedureDefinitionName == "write" || j.procedureDefinitionName == "writeln" {
		j.addInvokeVirtualPrintWithType()
	}
}

func (j *JASM) StartBlock() {
	if j.procedureDefinitionName == "" {
		// Main block.
		j.startMain()
	}
}

func (j *JASM) FinishBlock() {
	if j.procedureDefinitionName == "" {
		// Main block.
		j.finishMain()
	}

	j.procedureDefinitionName = ""
}

func (j *JASM) NewConstantString(constant string) {
	j.addLdcStringOpcode(constant)
}

func (j *JASM) NewConstantInteger(constant string) {
	j.addSiPushOpcode(constant)
}
func (j *JASM) StartIfStatement() {
	j.elseLabel = j.newLabel()
	j.endIfLabel = j.newLabel()
}

func (j *JASM) EnterThenStatement() {
	j.addOpcode("ifeq", j.elseLabel)
}

func (j *JASM) FinishThenStatement() {
	j.addOpcode("goto", j.endIfLabel)
	j.addLabel(j.elseLabel)
}

func (j *JASM) FinishIfStatement() {
	j.addLabel(j.endIfLabel)
}

func (j *JASM) AddOperatorOpcode(op string) {
	pt1 := j.pst.Pop()
	pt2 := j.pst.Pop()
	if pt1 != pt2 {
		j.addOpcode("invalid types")
		return
	}

	switch {
	case op == "and":
		switch pt1 {
		case Boolean:
			j.addOpcode("iand")
			j.pst.Push(Boolean)
		default:
			j.addOpcode("invalid type in boolean operator")
		}
	case op == "or":
		switch pt1 {
		case Boolean:
			j.addOpcode("ior")
			j.pst.Push(Boolean)
		default:
			j.addOpcode("invalid type in boolean operator")
		}
	case op == "*":
		switch pt1 {
		case Integer:
			j.genMulIntegers()
		default:
			j.addOpcode("invalid type in mul")
		}
	case op == "/":
		switch pt1 {
		case Integer:
			j.genDivIntegers()
		default:
			j.addOpcode("invalid type in div")
		}
	case op == "+":
		switch pt1 {
		case String:
			j.genAddStrings()
		case Integer:
			j.genAddIntegers()
		default:
			j.addOpcode("invalid type in add")
		}
	case op == "-":
		switch pt1 {
		case Integer:
			j.genSubIntegers()
		default:
			j.addOpcode("invalid type in sub")
		}
	case op == ">":
		switch pt1 {
		case Integer:
			j.genBooleanOperatorTpl("if_icmple")
		default:
			j.addOpcode("invalid type in comparison")
		}
	case op == "<":
		switch pt1 {
		case Integer:
			j.genBooleanOperatorTpl("if_icmpge")
		default:
			j.addOpcode("invalid type in comparison")
		}
	case op == ">=":
		switch pt1 {
		case Integer:
			j.genBooleanOperatorTpl("if_icmplt")
		default:
			j.addOpcode("invalid type in comparison")
		}
	case op == "<=":
		switch pt1 {
		case Integer:
			j.genBooleanOperatorTpl("if_icmpgt")
		default:
			j.addOpcode("invalid type in comparison")
		}
	case op == "=":
		switch pt1 {
		case Integer:
			j.genBooleanOperatorTpl("if_icmpne")
		default:
			j.addOpcode("invalid type in comparison")
		}
	case op == "<>":
		switch pt1 {
		case Integer:
			j.genBooleanOperatorTpl("if_icmpeq")
		default:
			j.addOpcode("invalid type in comparison")
		}
	}
}

func (j *JASM) AddUnaryOperatorOpcode(op string) {
	pt1 := j.pst.Pop()
	if pt1 != Boolean {
		j.addOpcode("invalid type in unary operator")
		return
	}

	switch op {
	case "not":
		lfalse := j.newLabel()
		lnext := j.newLabel()
		j.addOpcode("ifne", lfalse)
		j.addPushTrue()
		j.addGotoOpcode(lnext)
		j.addLabel(lfalse)
		j.addPushFalse()
		j.addLabel(lnext)
		j.pst.Push(Boolean)
	}
}

func (j *JASM) Code() string {
	return j.code.Code()
}

func (j *JASM) startMain() {
	j.addLine("public static main([java/lang/String)V {")
	j.incTab()
}

func (j *JASM) addOpcode(opcode string, parameters ...string) {
	params := strings.Join(parameters, " ")

	j.addLine(fmt.Sprintf("%s %s", opcode, params))
}

func (j *JASM) addLdcStringOpcode(text string) {
	j.addOpcode("ldc", text)
	j.pst.Push(String)
}

func (j *JASM) addSiPushOpcode(number string) {
	j.addOpcode("sipush", number)
	j.pst.Push(Integer)
}

func (j *JASM) addPushTrue() {
	j.addOpcode("iconst 1")
}

func (j *JASM) addPushFalse() {
	j.addOpcode("iconst 0")
}

func (j *JASM) addGotoOpcode(label string) {
	j.addOpcode("goto", label)
}

func (j *JASM) addInvokeVirtualPrintWithType() {
	pt := j.pst.Pop()
	if pt == String {
		j.addOpcode("invokevirtual", "java/io/PrintStream.print(java/lang/String)V")
	} else if pt == Integer {
		j.addOpcode("invokevirtual", "java/io/PrintStream.print(I)V")
	} else {
		j.addOpcode("undefined type in write/writeln")
	}
}

func (j *JASM) addInvokeVirtualPrintln() {
	j.addOpcode("invokevirtual", "java/io/PrintStream.println()V")
}

func (j *JASM) addStaticPrintStream() {
	j.addOpcode("getstatic", "java/lang/System.out", "java/io/PrintStream")
}

func (j *JASM) addLabel(label string) {
	j.addLine(fmt.Sprintf("%s:", label))
}

func (j *JASM) finishMain() {
	j.addLine("return")
	j.decTab()
	j.addLine("}")
}

func (j *JASM) startInvokeDynamic(param string) {
	j.addLine(fmt.Sprintf("invokedynamic %s {", param))
	j.incTab()
}

func (j *JASM) finishInvokeDynamic() {
	j.decTab()
	j.addLine("}")
}

func (j *JASM) newLabel() string {
	j.labelID++
	return fmt.Sprintf("L%d", j.labelID)
}

func (j *JASM) addLine(line string) {
	j.code.AddLine(line)
}

func (j *JASM) incTab() {
	j.code.IncTab()
}

func (j *JASM) decTab() {
	j.code.DecTab()
}

func (j *JASM) genAddStrings() {
	j.startInvokeDynamic(`makeConcatWithConstants(java/lang/String, java/lang/String)java/lang/String`)
	j.addOpcode(`invokestatic java/lang/invoke/StringConcatFactory.makeConcatWithConstants(java/lang/invoke/MethodHandles$Lookup, java/lang/String, java/lang/invoke/MethodType, java/lang/String, [java/lang/Object)java/lang/invoke/CallSite`)
	j.addOpcode(`[""]`)
	j.finishInvokeDynamic()
	j.pst.Push(String)
}

func (j *JASM) genAddIntegers() {
	j.addOpcode("iadd")
	j.pst.Push(Integer)
}

func (j *JASM) genSubIntegers() {
	j.addOpcode("isub")
	j.pst.Push(Integer)
}

func (j *JASM) genMulIntegers() {
	j.addOpcode("imul")
	j.pst.Push(Integer)
}

func (j *JASM) genDivIntegers() {
	j.addOpcode("idiv")
	j.pst.Push(Integer)
}

func (j *JASM) genBooleanOperatorTpl(ifOpcode string) {
	lfalse := j.newLabel()
	lnext := j.newLabel()
	j.addOpcode(ifOpcode, lfalse)
	j.addPushTrue()
	j.addGotoOpcode(lnext)
	j.addLabel(lfalse)
	j.addPushFalse()
	j.addLabel(lnext)
	j.pst.Push(Boolean)
}
